# override default cmf dynamic router with our implementation (with support for Meta Article)
parameters:
    cmf_routing.dynamic_router.class: SWP\Bundle\WebRendererBundle\Routing\MetaRouter

services:
    swp_webrenderer.listener.active_theme:
        class: SWP\Bundle\WebRendererBundle\EventListener\ActiveThemeListener
        arguments:
            - "@sylius.theme.repository"
            - "@sylius.theme.context"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    swp_webrenderer.detection.device_detection:
        class: SWP\Bundle\WebRendererBundle\Detection\DeviceDetection

    sylius.theme.locator.application_resource:
        class: SWP\Bundle\WebRendererBundle\Locator\ApplicationResourceLocator
        arguments:
            - "@filesystem"
            - "@swp_webrenderer.detection.device_detection"
