services:
    swp_template_engine_loader_chain:
        class: SWP\TemplateEngineBundle\Gimme\Loader\ChainLoader

    swp_template_engine_loader_article:
        class: SWP\TemplateEngineBundle\Gimme\Loader\ArticleLoader
        arguments:
            - %kernel.root_dir%
        tags:
            - { name: swp.meta_loader }

    swp_template_engine_twig_extension.gimme:
        class: SWP\TemplateEngineBundle\Twig\Extension\GimmeExtension
        public: false
        arguments:
            - @swp_template_engine_loader_chain
        tags:
            - { name: twig.extension }
