SWP\Bundle\ContentBundle\Model\ArticleAuthor:
    type: mappedSuperclass
    table: swp_author
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            nullable: true
    oneToOne:
        avatar:
            targetEntity: SWP\Bundle\ContentBundle\Model\AuthorMediaInterface
            joinColumn:
                name: author_media_id
                referencedColumnName: id
                nullable: true
