SWP\Bundle\ContentBundle\Doctrine\ORM\Article:
    type: entity
    table: swp_article
    repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ORM\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slug:
            type: string
        body:
            type: string
        title:
            type: string
        lead:
            type: string
            nullable: true
        templateName:
            type: string
            nullable: true
        locale:
            type: string
        status:
            type: string
        createdAt:
            type: date
        updatedAt:
            type: date
            nullable: true
        deletedAt:
            type: date
            nullable: true
        publishStartDate:
            type: date
            nullable: true
        publishEndDate:
            type: date
            nullable: true
        publishedAt:
            type: date
            nullable: true
        isPublishable:
            type: boolean
        metadata:
            type: string
            nullable: true
#    referenceOne:
#        route:
#            targetDocument: \SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\Route
#            strategy: hard
#    referrers:
#        media:
#            referringDocument: SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\ArticleMedia
#            referencedBy: article
#            cascade: [remove]
