SWP\Bundle\ContentBundle\Doctrine\ORM\ImageRendition:
    type: entity
    table: swp_image_rendition
    #repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ORM\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        width:
            type: integer
        height:
            type: integer
        name:
            type: string
    manyToOne:
        image:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\Image
            inversedBy: renditions
            joinColumn:
                name: image_id
                referencedColumnName: id
        media:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\ArticleMedia
            inversedBy: renditions
            joinColumn:
                name: media_id
                referencedColumnName: id