nelmio_api_doc:
  documentation:
    info:
      title: Superdesk Publisher
      version: 2.x
    schemes: [http, https]
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: []
  areas:
    path_patterns: [ ^/api(?!/doc/$) ]
