php:
    build: docker/php-fpm
    expose:
        - 9000:9000
    command: composer
    volumes:
        - .:/var/www/webrenderer
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes:
        - .:/var/www/webrenderer
        - logs/webrenderer:/var/www/webrenderer/app/logs
        - logs/nginx/:/var/log/nginx
    tty: true
