SWP\WebRendererBundle\Entity\PageContent:
    type: entity
    table: null
    repositoryClass: SWP\WebRendererBundle\Entity\PageContentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contentPath:
            column: content_path
            type: string
            nullable: true
    manyToOne:
        page:
            targetEntity: SWP\WebRendererBundle\Entity\Page
            inversedBy: contents
            joinColumn:
                name: page_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
