swp_api_settings_list:
    path: /api/{version}/settings/
    controller: SWP\Bundle\SettingsBundle\Controller\SettingsController::list
    defaults: { version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [GET]

swp_api_settings_revert:
    path: /api/{version}/settings/revert/{scope}
    controller: SWP\Bundle\SettingsBundle\Controller\SettingsController::revert
    defaults: { version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [POST]

swp_api_settings_update:
    path: /api/{version}/settings/
    controller: SWP\Bundle\SettingsBundle\Controller\SettingsController::update
    defaults: { version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [PATCH]

swp_api_settings_bulk_update:
    path: /api/{version}/settings/bulk/
    controller: SWP\Bundle\SettingsBundle\Controller\SettingsController::bulk
    defaults: { version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [PATCH]
