version: "3.7"

services:
    php:
        env_file:
            - .env.test
    test-api:
        image: node:10-alpine
        volumes:
            - ../../src/SWP/Bundle/CoreBundle/Tests/Functional/Resources:/app:rw
        working_dir: /app
        command: sh -c "npm install json-server && nohup node server.js"
