parameters:
    swp.provider.route.class: SWP\Bundle\ContentBundle\Provider\ORM\RouteProvider
    swp.provider.article.class: SWP\Bundle\ContentBundle\Provider\ORM\ArticleProvider

services:
    swp.provider.route:
        class: '%swp.provider.route.class%'
        arguments:
            - '@swp.repository.route'
            - '@doctrine'
            - '@cmf_routing.orm_candidates'
            - '%cmf_routing.dynamic.persistence.orm.route_class%'
        calls:
            - [setManagerName, ['%cmf_routing.dynamic.persistence.orm.manager_name%']]
            - [setRouteCollectionLimit, ['%cmf_routing.route_collection_limit%']]

    swp.provider.article:
        class: '%swp.provider.article.class%'
        arguments:
            - '@swp.repository.article'
