swp_api_content_list_related_articles:
  path: /api/{version}/content/articles/{id}/related/
  defaults: { _controller: SWPContentBundle:RelatedArticle:list, version: v2 }
  requirements:
    id: '\d+'
  methods: [GET]
  options:
    expose: true

swp_content:
  resource: '@SWPContentBundle/Controller'
  type: annotation
