SWP\Component\Bridge\Model\Author:
    type: mappedSuperclass
    fields:
        name:
            type: string
        role:
            type: string
        biography:
            type: text
            nullable: true
        avatarUrl:
            type: string
            nullable: true
        jobTitle:
            type: array
        twitter:
            type: string
            nullable: true
        facebook:
            type: string
            nullable: true
        instagram:
            type: string
            nullable: true
