SWP\Component\Bridge\Model\Item:
    type: mappedSuperclass
    table: swp_item
    repositoryClass: SWP\Bundle\BridgeBundle\Doctrine\ORM\ItemRepository
    fields:
        name:
            type: string
            nullable: true
        body:
            type: text
            nullable: true
        bodyText:
            type: text
            nullable: true
        usageTerms:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        package:
            targetEntity: SWP\Component\Bridge\Model\PackageInterface
            inversedBy: items
            joinColumn:
                onDelete: CASCADE
        group:
            targetEntity: SWP\Component\Bridge\Model\GroupInterface
            inversedBy: items
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        renditions:
            targetEntity: SWP\Component\Bridge\Model\RenditionInterface
            cascade: ["all"]
            mappedBy: item
