SWP\Component\Bridge\Model\Package:
    type: mappedSuperclass
    table: swp_package
    repositoryClass: SWP\Bundle\BridgeBundle\Doctrine\ORM\PackageRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
        edNote:
            type: text
            nullable: true
    uniqueConstraints:
        swp_package_guid_idx:
            columns: [ guid ]
    oneToMany:
        items:
            targetEntity: SWP\Component\Bridge\Model\ItemInterface
            cascade: ["all"]
            orphanRemoval: true
            mappedBy: package
        groups:
            targetEntity: SWP\Component\Bridge\Model\GroupInterface
            cascade: ["all"]
            orphanRemoval: true
            mappedBy: package
        externalData:
            targetEntity: SWP\Component\Bridge\Model\ExternalData
            cascade: ["all"]
            orphanRemoval: true
            mappedBy: package
