SWP\Bundle\CoreBundle\Model\MenuItem:
    exclusion_policy: ALL
    properties:
        route:
            expose: true
    relations:
        - rel: self
          href:
                route: swp_api_core_get_menu
                parameters:
                    id: expr(object.getId())
