properties:
  id:
    type: integer
  name:
    type: string
  scope:
    type: string
  value:
    type: string
  owner:
    type: integer
  created_at:
    type: string
    format: date-time
  updated_at:
    type: string
    format: date-time
type: object
