post:
  summary: Revert settings to defaults by scope
  parameters:
    - name: version
      in: path
      required: true
      schema:
        type: string
    - name: scope
      in: path
      required: true
      schema:
        type: string
  responses:
    '204':
      description: Returned on success.
  tags:
    - settings
