Knp\Menu\MenuItem:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
            type: string
        uri:
            expose: true
            type: string
        label:
            expose: true
            type: string
