SWP\Component\Bridge\Model\Item:
    exclusion_policy: ALL
    properties:
        usageTerms:
            expose: true
            type: string
            serialized_name: usageterms
            groups: [api]
        items:
            expose: true
            serialized_name: associations
            type: ArrayCollection<string,SWP\Component\Bridge\Model\Item>
            groups: [deserialization]
        renditions:
            expose: true
            serialized_name: renditions
            type: ArrayCollection<string,SWP\Component\Bridge\Model\Rendition>
            groups: [deserialization]

    virtual_properties:
        getItemsArray:
            serialized_name: associations
            type: array
            groups: [api]
        getRenditionsArray:
            serialized_name: renditions
            type: array
            groups: [api]
