services:
    GuzzleHttp\Client:
        arguments:
            -
                verify: false
        public: false

    SWP\Bundle\CoreBundle\Adapter\CompositeOutputChannelAdapter:
        public: true

    SWP\Bundle\CoreBundle\Adapter\WordpressAdapter:
        public: true
        arguments:
            - '@GuzzleHttp\Client'
            - '@swp.repository.external_article'
            - '@swp.object_manager.external_article'
            - '@swp_content_bundle.manager.media'
        tags:
            - { name: swp.output_channel_adapter, alias: wordpress_adapter }
