SWP\Bundle\CoreBundle\Model\Tenant:
    type: entity
    table: swp_tenant
    fields:
        themeName:
            type: string
            nullable: true
    manyToOne:
        organization:
            targetEntity: SWP\Bundle\CoreBundle\Model\Organization
            inversedBy: tenants
            cascade: ["remove"]
            joinColumn:
                name: organization_id
                referencedColumnName: id
                onDelete: CASCADE
